#https://github.com/getredash/setup/blob/master/data/compose.yaml

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    redash-postgres:
      condition: service_healthy
    redash-redis:
      condition: service_healthy
  env_file: .env
  environment:
    REDASH_DATABASE_URL: postgresql://${REDASH_POSTGRES_USER}:${REDASH_POSTGRES_PASSWORD}@redash-postgres:5432/${REDASH_POSTGRES_DB}
    REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
    REDASH_REDIS_URL: redis://redash-redis:6379/0
  restart: unless-stopped

services:
  data-generator:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:${POSTGRES_INNER_PORT}"
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c port=${POSTGRES_INNER_PORT}
    volumes:
      - ./db:/docker-entrypoint-initdb.d:ro
      - postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_INNER_PORT}"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redash-postgres:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${REDASH_POSTGRES_DB}
      POSTGRES_USER: ${REDASH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REDASH_POSTGRES_PASSWORD}
    volumes:
      - redash_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U ${REDASH_POSTGRES_USER} -d ${REDASH_POSTGRES_DB}"]
      interval: 20s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redash-redis:
    image: redis:7-alpine
    volumes:
      - redash_redis_data:/data
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 30s
      start_interval: 5s
    restart: unless-stopped
  
  redash-server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"

  redash-scheduler:
    <<: *redash-service
    command: scheduler

  redash-workers:
    <<: *redash-service
    command: worker

volumes:
  postgres:
  redash_postgres_data:
  redash_redis_data:
  pgadmin_data:


