#https://github.com/getredash/setup/blob/master/data/compose.yaml

x-redash-service: &redash-service
  image: redash/redash:latest
  depends_on:
    - postgres
    - redis
  env_file: .env
  environment:
    REDASH_DATABASE_URL: postgresql://${REDASH_POSTGRES_USER}:${REDASH_POSTGRES_PASSWORD}@redash-postgres:5432/${REDASH_POSTGRES_DB}
    REDASH_COOKIE_SECRET: ${REDASH_COOKIE_SECRET}
    REDASH_SECRET_KEY: ${REDASH_SECRET_KEY}
  restart: unless-stopped
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5001"
  scheduled_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
  redash-postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: redash_postgres
    environment:
      POSTGRES_DB: ${REDASH_POSTGRES_DB}
      POSTGRES_USER: ${REDASH_POSTGRES_USER}
      POSTGRES_PASSWORD: ${REDASH_POSTGRES_PASSWORD}
    volumes:
      - redash_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U ${REDASH_POSTGRES_USER} -d ${REDASH_POSTGRES_DB}" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redash_redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 20s
      timeout: 10s
      retries: 10
    restart: unless-stopped
  postgres:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_HOST}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:${POSTGRES_INNER_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c port=${POSTGRES_INNER_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_INNER_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  redash-worker:
    image: redash/redash:latest
    environment:
      REDIS_URL: "redis://redis-1:6379/0"
      OTHER_VAR: "value"

volumes:
  redash_postgres_data:
  redash_redis_data:
  postgres_data:


